package net.dirox.auluxa.extras;

/**
 * Created by an on 6/9/2017.
 */

public class Enumes {
    public enum FragmentType {

        FRAGMENT_DEFAULT_NULL("FRAGMENT_DEFAULT_NULL"),
        FRAGMENT_ROOM_CENTRE("FRAGMENT_ROOM_CENTRE"),
        FRAGMENT_ROOM_CENTRE_CLIMATE("FRAGMENT_ROOM_CENTRE_CLIMATE"),
        FRAGMENT_ROOM_CENTRE_CLIMATE_CONTROL("FRAGMENT_ROOM_CENTRE_CLIMATE_CONTROL"),
        FRAGMENT_ROOM_CENTRE_CLIMATE_SCHEDULE("FRAGMENT_ROOM_CENTRE_CLIMATE_SCHEDULE"),
        FRAGMENT_CLIMATE_SLEEP_TIMER("FRAGMENT_CLIMATE_SLEEP_TIMER"),
        FRAGMENT_CLIMATE_SCHEDULING("FRAGMENT_CLIMATE_SCHEDULING"),
        FRAGMENT_CLIMATE_SCHEDULING_DETAIL("FRAGMENT_CLIMATE_SCHEDULING_DETAIL"),
        FRAGMENT_ROOM_CENTRE_LIGHTS("FRAGMENT_ROOM_CENTRE_LIGHTS"),
        FRAGMENT_ROOM_CENTRE_AUDIO("FRAGMENT_ROOM_CENTRE_AUDIO"),
        FRAGMENT_ROOM_CENTRE_AUDIO_SETTINGS("FRAGMENT_ROOM_CENTRE_AUDIO_SETTINGS"),
        FRAGMENT_ROOM_CENTRE_AUDIO_DEVICES("FRAGMENT_ROOM_CENTRE_AUDIO_DEVICES"),
        FRAGMENT_ROOM_CENTRE_AUDIO_CREATE_GROUP("FRAGMENT_ROOM_CENTRE_AUDIO_CREATE_GROUP"),
        FRAGMENT_ROOM_CENTRE_VIDEO("FRAGMENT_ROOM_CENTRE_VIDEO"),
        FRAGMENT_ROOM_CENTRE_VIDEO_APLIFIER("FRAGMENT_ROOM_CENTRE_VIDEO_APLIFIER"),
        FRAGMENT_ROOM_CENTRE_VIDEO_CABLE_TV("FRAGMENT_ROOM_CENTRE_VIDEO_CABLE_TV"),
        FRAGMENT_ROOM_CENTRE_VIDEO_APPLE_TV("FRAGMENT_ROOM_CENTRE_VIDEO_APPLE_TV"),
        FRAGMENT_ROOM_CENTRE_VIDEO_MATRIX("FRAGMENT_ROOM_CENTRE_VIDEO_MATRIX"),
        FRAGMENT_ROOM_CENTRE_VIDEO_TV_REMOTE("FRAGMENT_ROOM_CENTRE_VIDEO_TV_REMOTE"),
        FRAGMENT_ROOM_CENTRE_VIDEO_DVD_REMOTE("FRAGMENT_ROOM_CENTRE_VIDEO_DVD_REMOTE"),
        FRAGMENT_ROOM_CENTRE_VIDEO_MEDIA_SERVER("FRAGMENT_ROOM_CENTRE_VIDEO_MEDIA_SERVER"),
        FRAGMENT_ROOM_CENTRE_SHADES("FRAGMENT_ROOM_CENTRE_SHADES"),
        FRAGMENT_ROOM_CENTRE_OTHERS("FRAGMENT_ROOM_CENTRE_OTHERS"),
        FRAGMENT_MAIN_HOME("FRAGMENT_MAIN_HOME"),
        FRAGMENT_SCHEDULING("FRAGMENT_SCHEDULING"),
        FRAGMENT_EDIT_TARGET("FRAGMENT_EDIT_TARGET"),
        FRAGMENT_SETTING_MAIN("FRAGMENT_SETTING_MAIN"),
        FRAGMENT_SETTING_LANGUAGE("FRAGMENT_SETTING_LANGUAGE"),
        FRAGMENT_SETTING_CLIMATE("FRAGMENT_SETTING_CLIMATE"),
        FRAGMENT_SETTING_DATE_TIME("FRAGMENT_SETTING_DATE_TIME"),
        FRAGMENT_SETTING_TIMEZONE("FRAGMENT_SETTING_TIMEZONE"),
        FRAGMENT_SETTING_NOTIFICATIONS("FRAGMENT_SETTING_NOTIFICATIONS"),
        FRAGMENT_SETTING_NOTIFICATIONS_ENERGY("FRAGMENT_SETTING_NOTIFICATIONS_ENERGY"),
        FRAGMENT_SETTING_NOTIFICATIONS_ROOMS("FRAGMENT_SETTING_NOTIFICATIONS_ROOMS"),
        FRAGMENT_SETTING_ROOM_IMAGE("FRAGMENT_SETTING_ROOM_IMAGE"),
        FRAGMENT_SETTING_DEVICE_LIST("FRAGMENT_SETTING_DEVICE_LIST"),
        FRAGMENT_SETTING_RECENTLY_ADDED("FRAGMENT_SETTING_RECENTLY_ADDED"),
        FRAGMENT_SETTING_ADD_DEVICES("FRAGMENT_SETTING_ADD_DEVICES"),
        FRAGMENT_SETTING_THIRD_PARTY("FRAGMENT_SETTING_THIRD_PARTY"),
        FRAGMENT_SETTING_USER_MANAGEMENT("FRAGMENT_SETTING_USER_MANAGEMENT"),
        FRAGMENT_SETTING_LIST_USER_MANAGEMENT("FRAGMENT_SETTING_LIST_USER_MANAGEMENT"),

        // Setting Climate Devices
        FRAGMENT_SETTING_DEVICE_CLIMATE("FRAGMENT_SETTING_DEVICE_CLIMATE"),
        FRAGMENT_SETTING_CLIMATE_DEVICE_THERMOSTAT_PANEL("FRAGMENT_SETTING_CLIMATE_DEVICE_THERMOSTAT_PANEL"),
        FRAGMENT_SETTING_CLIMATE_DEVICE_GENERAL("FRAGMENT_SETTING_CLIMATE_DEVICE_GENERAL"),
        FRAGMENT_SETTING_CLIMATE_DEVICE_ROOMS_GENERAL("FRAGMENT_SETTING_CLIMATE_DEVICE_ROOMS_GENERAL"),
        FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_HUMIDITY("FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_HUMIDITY"),
        FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_TEMP_SENSOR("FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_TEMP_SENSOR"),
        FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_TEMP_HUMIDITY_SENSOR("FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_TEMP_HUMIDITY_SENSOR"),
        FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_IR_NODE("FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_IR_NODE"),
        FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_IR_NODE_CATEGORY("FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_IR_NODE_CATEGORY"),
        FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_IR_NODE_MANUFACTURER("FRAGMENT_SETTING_CLIMATE_SELECT_DEVICE_IR_NODE_MANUFACTURER"),

        // Setting Audio Devices
        FRAGMENT_SETTING_DEVICE_AUDIO("FRAGMENT_SETTING_DEVICE_AUDIO"),
        FRAGMENT_SETTING_AUDIO_DEVICE_GENERAL("FRAGMENT_SETTING_AUDIO_DEVICE_GENERAL"),
        FRAGMENT_SETTING_AUDIO_DEVICE_CONNECT("FRAGMENT_SETTING_AUDIO_DEVICE_CONNECT"),
        FRAGMENT_SETTING_AUDIO_DEVICE_SETTINGS("FRAGMENT_SETTING_AUDIO_DEVICE_SETTINGS"),
        FRAGMENT_SETTING_AUDIO_DEVICE_MAPPING("FRAGMENT_SETTING_AUDIO_DEVICE_MAPPING"),
        FRAGMENT_SETTING_AUDIO_DEVICE_HDMI("FRAGMENT_SETTING_AUDIO_DEVICE_HDMI"),

        // Setting Video Devices
        FRAGMENT_SETTING_DEVICE_VIDEO("FRAGMENT_SETTING_DEVICE_VIDEO"),
        FRAGMENT_SETTING_VIDEO_DEVICE_GENERAL("FRAGMENT_SETTING_VIDEO_DEVICE_GENERAL"),
        FRAGMENT_SETTING_VIDEO_SELECT_DEVICE("FRAGMENT_SETTING_VIDEO_SELECT_DEVICE"),
        FRAGMENT_SETTING_VIDEO_ROOMS("FRAGMENT_SETTING_VIDEO_ROOMS"),
        FRAGMENT_SETTING_VIDEO_CODE("FRAGMENT_SETTING_VIDEO_CODE"),
        FRAGMENT_SETTING_VIDEO_SELECT_CATEGORY("FRAGMENT_SETTING_VIDEO_SELECT_CATEGORY"),
        FRAGMENT_SETTING_VIDEO_SELECT_MANUFACTURER("FRAGMENT_SETTING_VIDEO_SELECT_MANUFACTURER"),

        //Security
        FRAGMENT_SECURITY("FRAGMENT_SECURITY"),
        FRAGMENT_SECURITY_ALARM("FRAGMENT_SECURITY_ALARM"),
        FRAGMENT_SECURITY_DOOR_LOCK("FRAGMENT_SECURITY_DOOR_LOCK"),
        FRAGMENT_SECURITY_SURVELLIANCE("FRAGMENT_SECURITY_SURVELLIANCE"),
        FRAGMENT_SECURITY_VIDEO_PHONE("FRAGMENT_SECURITY_VIDEO_PHONE"),
        FRAGMENT_SECURITY_AIRBNB("FRAGMENT_SECURITY_AIRBNB"),
        FRAGMENT_ENERGY("FRAGMENT_ENERGY"),
        FRAGMENT_SCENE_CREATE_STEP_1("FRAGMENT_SCENE_CREATE_STEP_1"),
        FRAGMENT_SCENE_CREATE_STEP_2("FRAGMENT_SCENE_CREATE_STEP_2"),
        FRAGMENT_SCENE_CREATE_RENAME("FRAGMENT_SCENE_CREATE_RENAME"),
        FRAGMENT_SCENE_CREATE_SCHEDULE("FRAGMENT_SCENE_CREATE_SCHEDULE"),
        FRAGMENT_SCENE_CREATE_SEQUENCE("FRAGMENT_SCENE_CREATE_SEQUENCE"),
        FRAGMENT_SCENE_CREATE_ROOMS("FRAGMENT_SCENE_CREATE_ROOMS"),
        FRAGMENT_SCENE_CREATE_ROOM_DETAIL("FRAGMENT_SCENE_CREATE_ROOM_DETAIL"),
        FRAGMENT_SCENE_CREATE_ROOM_VIDEO_LIST("FRAGMENT_SCENE_CREATE_ROOM_VIDEO_LIST"),
        FRAGMENT_SCENE_CREATE_ROOM_VIDEO_LIST_SEQUENCE("FRAGMENT_SCENE_CREATE_ROOM_VIDEO_LIST_SEQUENCE"),
        FRAGMENT_SCENE_CREATE_ROOM_VIDEO_ADD_SEQUENCE("FRAGMENT_SCENE_CREATE_ROOM_VIDEO_ADD_SEQUENCE"),
        FRAGMENT_SCENE_CREATE_ROOM_SECURITY("FRAGMENT_SCENE_CREATE_ROOM_SECURITY"),
        FRAGMENT_SCENE_CREATE_ROOM_CLIMATE("FRAGMENT_SCENE_CREATE_ROOM_CLIMATE"),
        FRAGMENT_SCENE_CREATE_LIGHT("FRAGMENT_SCENE_CREATE_LIGHT"),
        FRAGMENT_SCENE_CREATE_SHADE("FRAGMENT_SCENE_CREATE_SHADE"),
        FRAGMENT_SECURITY_PENDING_BLUETOOTH_KEY("FRAGMENT_SECURITY_PENDING_BLUETOOTH_KEY"),

        // Settings Lights
        FRAGMENT_SETTING_DEVICE_LIGHTS("FRAGMENT_SETTING_DEVICE_LIGHTS"),
        FRAGMENT_ONE_BUTTON_ON_OFF("FRAGMENT_ONE_BUTTON_ON_OFF"),
        FRAGMENT_TWO_BUTTON_ON_OFF("FRAGMENT_TWO_BUTTON_ON_OFF"),
        FRAGMENT_FOUR_BUTTON_ON_OFF("FRAGMENT_FOUR_BUTTON_ON_OFF"),
        FRAGMENT_ON_OFF_NODE("FRAGMENT_ON_OFF_NODE"),
        FRAGMENT_ONE_BUTTON_DIMMING("FRAGMENT_ONE_BUTTON_DIMMING"),
        FRAGMENT_TWO_BUTTON_DIMMING("FRAGMENT_TWO_BUTTON_DIMMING"),
        FRAGMENT_DIMMING_NODE("FRAGMENT_DIMMING_NODE"),
        FRAGMENT_ONE_BUTTON_PANEL("FRAGMENT_ONE_BUTTON_PANEL"),
        FRAGMENT_TWO_BUTTON_PANEL("FRAGMENT_TWO_BUTTON_PANEL"),
        FRAGMENT_FOUR_BUTTON_PANEL("FRAGMENT_FOUR_BUTTON_PANEL"),
        FRAGMENT_ONE_BUTTON_DIMMING_PANEL("FRAGMENT_ONE_BUTTON_DIMMING_PANEL"),
        FRAGMENT_TWO_BUTTON_DIMMING_PANEL("FRAGMENT_TWO_BUTTON_DIMMING_PANEL"),

        // Settings Shades
        FRAGMENT_SETTING_DEVICE_SHADES("FRAGMENT_SETTING_DEVICE_SHADES"),
        FRAGMENT_ONE_BUTTON_SHADES("FRAGMENT_ONE_BUTTON_SHADES"),
        FRAGMENT_TWO_BUTTON_SHADES("FRAGMENT_TWO_BUTTON_SHADES"),
        FRAGMENT_ONE_BUTTON_SHADES_PANEL("FRAGMENT_ONE_BUTTON_SHADES_PANEL"),
        FRAGMENT_TWO_BUTTON_SHADES_PANEL("FRAGMENT_TWO_BUTTON_SHADES_PANEL"),
        FRAGMENT_SHADES_NODE("FRAGMENT_SHADES_NODE"),

        // Settings Security
        FRAGMENT_SETTING_DEVICE_SECURITY("FRAGMENT_SETTING_DEVICE_SECURITY"),
        FRAGMENT_AULUXA_DOOR_LOCK("FRAGMENT_AULUXA_DOOR_LOCK"),
        FRAGMENT_DOOR_LOCK("FRAGMENT_DOOR_LOCK"),
        FRAGMENT_ALARM("FRAGMENT_ALARM"),
        FRAGMENT_SENSOR("FRAGMENT_SENSOR"),
        FRAGMENT_DOOR_BELL("FRAGMENT_DOOR_BELL"),
        FRAGMENT_VIDEO_DOOR_PHONE("FRAGMENT_VIDEO_DOOR_PHONE"),
        FRAGMENT_SECURITY_ASSIGNED_LOCK_PIN("FRAGMENT_SECURITY_ASSIGNED_LOCK_PIN"),
        FRAGMENT_SECURITY_ASSIGNED_PIN("FRAGMENT_SECURITY_ASSIGNED_PIN"),
        FRAGMENT_SECURITY_DURATION_PIN("FRAGMENT_SECURITY_DURATION_PIN"),
        FRAGMENT_SECURITY_CREATE_LOCK_PIN("FRAGMENT_SECURITY_CREATE_LOCK_PIN"),
        FRAGMENT_SECURITY_CREATE_ONETIME_OR_PERMANENT_PIN("FRAGMENT_SECURITY_CREATE_ONETIME_OR_PERMANENT_PIN"),
        FRAGMENT_SECURITY_CREATE_DURATION_PIN("FRAGMENT_SECURITY_CREATE_DURATION_PIN"),
        FRAGMENT_ACTIVITY_LOG("FRAGMENT_ACTIVITY_LOG"),
        FRAGMENT_SECURITY_LOCK("FRAGMENT_SECURITY_LOCK"),
        FRAGMENT_SECURITY_LOCK_EDITNAME("FRAGMENT_SECURITY_LOCK_EDITNAME"),
        FRAGMNET_ADD_BLUETOOTH_KEY("FRAGMNET_ADD_BLUETOOTH_KEY"),
        FRAGMENT_CONNECT_TO_IGLOOHOME("FRAGMENT_CONNECT_TO_IGLOOHOME");

        final String mValue;

        FragmentType(String value) {
            mValue = value;
        }

        public String toString() {
            return mValue;
        }
    }

    public enum Direction {
        NONE("NONE"),
        LEFT_IN("LEFT_IN"),
        RIGHT_IN("RIGHT_IN"),
        RIGHT_IN_FLIP_OUT("RIGHT_IN_FLIP_OUT"),
        TOP_IN("TOP_IN"),
        BOTTOM_IN("BOTTOM_IN"),
        FLIP_IN("FLIP_IN"),
        FLIP_OUT("FLIP_OUT");

        final String mDirection;

        Direction(String value) {
            mDirection = value;
        }

        public String toString() {
            return mDirection;
        }
    }

}
